### ISSUE TITLE
oredict entries are registered slightly late

### ISSUE THREAD

**Issue by RCXcrafter** [DaedalusGame/EmbersRekindled#146]
Certain mods (especially jaopca) require oredict entries to registered before init in order to detect them for recipes. So for better mod compatibility I'd like all oredict registering to be moved to [here](https://github.com/DaedalusGame/EmbersRekindled/blob/b8686d5e5202ab3de632ef9c4ddbd704b9e20a2e/src/main/java/teamroots/embers/RegistryManager.java#L700).

**Comment by Davoleo** [comment]
lol, u sure are reporting this issue on many mods

**Comment by DaedalusGame** [comment]
i swear to god oredict should be registered in recipe registry, i'll check if it's not and move it there

**Comment by DaedalusGame** [comment]
yeah, oredict is done in recipe registry

**Comment by Davoleo** [comment]
yeah, what he says is that mods like JAOPCA, or even Mekanism needs oredict registration to be even earlier (right after item registration) and that's actually true

**Comment by DaedalusGame** [comment]
ree ok

**Comment by DaedalusGame** [comment]
Important note here ye who dare enter:

I believe ObjectHolders are populated after item registry is done. Embers doesn't use ObjectHolders (yet), but I still have to offer a chance for addon developers to register over Embers items. Mods that do use ObjectHolders cannot implement oredictionary registration in item registry, because it would leave unregistered items in the oredict (probably bad).

Oredict Registry now sits snuggly at item registry at **low priority** and will not move to a higher priority ever.

**Comment by Lgmrszd** [comment]
bruh
