### ISSUE TITLE
Incorrect ember energy transfer render on server

### ISSUE THREAD

**Issue by SSKirillSS** [DaedalusGame/EmbersRekindled#164]
Once I addressed a developer with a similar problem personally, but I could not find a specific solution. A few months later I tried to solve the problem on my own, but nothing succeeded either.

The principle of the problem is extremely simple - on the server embers energy transfer displayed incorrectly. Video-demo: https://youtu.be/KpLdvfLck50

**Versions:**
_EmbersRekindled-1.13-hotfix2
forge-1.12.2-14.23.5.2836-universal
spongeforge-1.12.2-2768-7.1.6-RC3616_

**Full modlist:**
![image](https://user-images.githubusercontent.com/38190325/57529379-6f5bd780-733d-11e9-9e1f-88df69cd3fce.png)

**Comment by DaedalusGame** [comment]
~~This might be an Optifine issue?~~
Nevermind, you're running Spongeforge, that would do it.

**Comment by gabizou** [comment]
Sorry but I'm at a complete loss of what I'm looking at. Because I know Sponge's codebase fairly well, I have an idea of what could be going on, but I'd need to know what sort of data is being sent to the client for those blocks/tiles, and what the expected results are supposed to show on the client versus what's being shown in the video. If you want, we can take this discussion to the SpongeForge issue itself since I'm fairly positive I'll be able to fix it there as it doesn't seem like something that needs changing in the mod itself.

**Comment by DaedalusGame** [comment]
I don't really know what I'm looking at either

The tiles and blocks are largely irrelevant here. But the ember orbs themselves are entities. They sync their positional data ~~and their destination~~. Every tick, it does some simple vector operations to calculate an expected motion vector that allows them to reach the target. It then interpolates 10% of that expected motion onto the current motion, making it travel at an arc towards the destination.

EDIT: 
oh, thats right, the positional data isn't actually synchronized, but it shouldn't matter since this is a server-side issue.

You can find the code [here](https://github.com/DaedalusGame/EmbersRekindled/blob/rekindled/src/main/java/teamroots/embers/entity/EntityEmberPacket.java)

**Comment by gabizou** [comment]
> They sync their positional data and their destination.

And where does that destination get set? I presume the destination is being set either by the TileEntities emitting them or something?

**Comment by DaedalusGame** [comment]
yes, the tile entity that emits them sets it using initCustom
