### ISSUE TITLE
[Question] EmbersRekindled & Soot config question

### ISSUE THREAD

**Issue by wamc2017** [DaedalusGame/EmbersRekindled#21]
Hi,

I would love to try the dev build, but I have two questions before upgrading from the old embers version:
- Are the itemids the same or should I start a new world?
- I think I read something in the commits about features which was brought over from Soot, should I disable some of the overrides in the Soot config before updating?

Thanks for looking into it and updating embers. :)

Best regards
wamc

**Comment by DaedalusGame** [comment]
Ids should stay the same, since the modid and resourcenames are all identical, but backup beforehand
Overrides from soot should all be disabled since i'm working on making those changes in embers instead. The only thing you currently lose is hearthcoil and dawnstone anvil CT support i think.

EDIT: actually two more things that won't work currently, machine upgrades for Embers machines will not work if the override is disabled, which also means the Alchemical Mixer will be defunct until upgrades are migrated. Now that I think about it, it's probably safe to keep overrides enabled for now.

**Comment by wamc2017** [comment]
Thanks, I will check it out with overrides enabled. :+1:
