### ISSUE TITLE
Extracting Ember from a Nether Portal

### ISSUE THREAD

**Issue by crazytobuildmc** [DaedalusGame/EmbersRekindled#49]
Self-explanatory. Basically a multiblock, highly efficient Ember bore for mid/lategame. You would build an 'Infernal Extractor' around a nether portal (the bigger the portal the faster it works). No fuel needed to run, just to start up. The idea being that if the Overworld's core is brimming with firey energy, the hellish atmosphere of The Nether must be swimming in it - so much so it will never run out. Ever.
PROS:
- does not consume ember from chunks.
- massively more efficient.

CONS:
- a full stack of blaze powder is used as an activation catalyst. The machine is also costly: see screenshots below for four stages of its construction around a 3x3 portal (must be an odd number: archaic lights, iron bars and magma block must be place in the centre).
- only buildable in the overworld. Will not form in other dimensions.
- If Mystical Mechanics is enabled, you will have to apply mechanical energy to moderate it: slowing it down over time. However, if not moderated sufficiently, the machine will violently explode with infernal power and Ember - enough to seriously ruin your day. Moderate too much, and the Extractor will grind to a halt. You have to carefully use redstone to run pulses of mechanical energy into the machine to run it efficiently. Otherwise, it just uses blaze powder as fuel (or both: configurable).

<a href="https://ibb.co/cj8p4p"><img src="https://thumb.ibb.co/cj8p4p/20180908165114_1.jpg" alt="20180908165114_1" border="0"></a> <a href="https://ibb.co/enpwjp"><img src="https://thumb.ibb.co/enpwjp/20180908165209_1.jpg" alt="20180908165209_1" border="0"></a> 
Ensure dawnstone is in corners, not obsidian
<a href="https://ibb.co/cdxSqU"><img src="https://thumb.ibb.co/cdxSqU/20180908165339_1.jpg" alt="20180908165339_1" border="0"></a> <a href="https://ibb.co/cHPe4p"><img src="https://thumb.ibb.co/cHPe4p/20180908165930_1.jpg" alt="20180908165930_1" border="0"></a>
Access blocks used as input for mechanical energy and blaze powder. Output from the inferno forge at the bottom. Speaking of which, ensure bore and forge are aligned with the middle of the portal. Blocks around forge do not scale with portal.

**Comment by Darkmega18** [comment]
plus one vote from me! :D 

On the same topic of more powerful ember bores and alternative ember mining, Can I suggest some kind of ability to stack multiple bores (up to 3?) to power up a standard bore allowing it to become more efficient just off hand and perhaps with the added effect of making the grinding bit look cooler with each extension? 

Since ember bore kinda just starts at one thing, then never gets stronger alternatives or upgrades, you just gotta spam more of them, which is kinda meh sometimes for lag, looks and logistics. :V then it could be the same deal with this infernal mining idea, more stacked bores, makes for go faster or run better but whatever it's activation or constant power requirements can be increase similarly if you can afford the costs to run it more.

**Comment by DaedalusGame** [comment]
a) There's "no Ember" in the nether according to the lore, which is also why quartz spawns in the overworld and the other materials can be made by alchemy
b) Ember in the overworld is infinite, only the rate varies over time
c) You can speed Ember Bores up with Catalytic Plugs and Mechanical Actuators

**Comment by crazytobuildmc** [comment]
wow im stupid... meh, at least I tried.

**Comment by Darkmega18** [comment]
we got dunked on by the power of lore. GG

**Comment by DaedalusGame** [comment]
the lore reason i gave is secondary, the main reasons why this is unlikely to make it in are that you can already power Ember Bores up to crackhead speeds and because having an "infinite" source of Ember in this structure, when the regular Bores are already infinite isn't as useful as expected.

Other problems include "only overworld" instead of any dimension with access to the nether (which makes it even less useful compared to the regular bore), and a full stack of blaze powder required as starting catalyst (thematic reasons aside, why blaze powder? are we using the mod's mechanics to get blaze powder somehow?)

I do like the idea of modulating a machine with mechanical power that needs to be carefully engineered, but I think that's going to be reserved for a different machine if anything :)

Just wanted to clarify my thoughts on this suggestion :)

**Comment by Darkmega18** [comment]
I think i just need to watch more updated showcases then. cause all this catalytic plugging and actuating and alchemying is pain and the finding of space and doing logistics of it all hurts my non automation mind. mod is hard. I'm one of those, "I like it go fast so I can just do it manual" people who sigh massive when redstone shenanigans is involved. :V

**Comment by crazytobuildmc** [comment]
(thematic reasons aside, why blaze powder? are we using the mod's mechanics to get blaze powder somehow?)
Because blaze powder is hot. The mob's called a Blaze for a reason. You have to get some heat going somehow, then it was going to draw it out. The idea wasn't to produce blaze powder per se, rather to give you a risk for failing to moderate it well. If you fail, you have to go back into literal hell and kill a bunch of heavy-breathing firey heads surrounded by firey rods. TL;DR do it right or die trying again.
Well, we were 'dunked on by lore' as it was said so wonderfully, so we may as well brick this closed door up: it ain't gonna be open again. At least the moderation idea flew well.
